### ISSUE TITLE
Crypto Resource Pack V1 Milestone

### ISSUE THREAD

**Issue by stevokk** [stevokk/stevokk.github.io#2]
Some tasks to bring the resource pack to a version 1 state:

- [ ] List Recommended applications
- [ ] List Youtube Accounts
- [ ] List Sub-Reddits & Combi link
- [ ] List Twitter Accounts
- [ ] List Telegram Channels
- [ ] List RSS feeds & news sites
- [ ] List exchanges w/ referral codes
- [ ] TA Resources
- [ ] List Wallets
- [ ] Pick header image
- [ ] List Chrome extensions
- [ ] Computer configuration tips
